# A name for your conda environment
name: edh-hackathon-env

# The channels conda will search for packages, in order of priority.
channels:
  - conda-forge
  - nodefaults

# A list of your project's dependencies
dependencies:
  # 1. Specify the Python version
  - python=3.10

  # 2. Core data science packages
  - matplotlib>=3.8,<4.0
  - plotly>=6.3.0,<7.0.0
  - pandas>=2.3.2,<3.0.0
  - numpy<2.0
  - scikit-learn>=1.5.0,<2.0.0
  - pyarrow>=16.0.0,<17.0.0
  - seaborn>=0.13.2,<0.14.0
  - networkx<3.3
  
  # 3. Jupyter and Plotly Rendering Dependencies (THE FIX)
  - jupyterlab>=4.0,<5.0       # The JupyterLab interface
  - ipykernel                   # The kernel for Jupyter
  - ipywidgets>=8.1.2,<9.0.0     # For interactive widgets
  - jupyterlab-plotly           # The key extension for Plotly in JupyterLab
  - nbformat

  # 4. It's good practice to add pip here for completeness
  - pip